%global     realname  Apache-Htgroup

Name:           perl-%{realname}
Version:        1.23
Release:        3%{?dist}
Summary:        Manage Apache authentication group files
License:        GPLv2+ or Artistic
URL:            http://search.cpan.org/dist/Apache-Htgroup/
Source0:        http://search.cpan.org/CPAN/authors/id/R/RB/RBOW/%{realname}-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Manage Apache htgroup files

%prep
%setup -q -n %{realname}-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
make test

%files
%doc README
%license LICENSE
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Aug 18 2015 Steven Hadfield <hadfieldster@gmail.com> 1.23-3
- RPM spec cleanup

* Fri Jul 6 2012 Steven Hadfield <StevenHadfield@letu.edu> 1.23-2
- RPM spec fixies

* Fri Feb 11 2011 Steven Hadfield <StevenHadfield@letu.edu> 1.23-1
- Updated to upstream 1.23

* Wed Nov 24 2010 Steven Hadfield <StevenHadfield@letu.edu> 1.22-1
- Specfile autogenerated by cpanspec 1.78.
