%define     realname  Apache-Htgroup

Name:           perl-%{realname}
Version:        1.23
Release:        2%{?dist}
Summary:        Manage Apache authentication group files
License:        GPLv2+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Apache-Htgroup/
Source0:        http://search.cpan.org/CPAN/authors/id/R/RB/RBOW/%{realname}-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Manage Apache htgroup files

%prep
%setup -q -n %{realname}-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%files
%defattr(-,root,root,-)
%doc LICENSE README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Jul 6 2012 Steven Hadfield <StevenHadfield@letu.edu> 1.23-2
- RPM spec fixies

* Fri Feb 11 2011 Steven Hadfield <StevenHadfield@letu.edu> 1.23-1
- Updated to upstream 1.23

* Wed Nov 24 2010 Steven Hadfield <StevenHadfield@letu.edu> 1.22-1
- Specfile autogenerated by cpanspec 1.78.
